name: CI

# This workflow runs whenever the code is pushed or pulled to the main or develop branches.
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v5
        # Set up environment and dependencies
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

        # Check code for formatting and syntax errors.
      - name: Run linter
        run: npm run lint
        continue-on-error: true

        # Build the project
      - name: Build
        run: npm run build

        # To verify that the build was successful
      - name: Check build output
        run: test -d .next
        shell: bash
